import '../components/ChatActionBar/style'
import '../components/ChatSettingDrawer/style'
import '../components/ChatHeader/style'
import '../components/ChatP2pMessageList/style'
import '../components/ChatMessageItem/style'
import '../components/ChatMessageInput/style'
import '../components/ChatAddMembers/style'
import '../components/ChatP2pSetting/style'
import '../components/ChatTeamSetting/style'
import '../components/ChatForwardModal/style'
import '../components/ChatTeamMemberModal/style'
import '../components/ChatGroupTransferModal/style'
import '../components/ChatCollectionList/style'
import '../components/ChatTopMsg/style'
import '../components/ChatAISearch/style'
import '../components/ChatAITranslate/style'

import '../../common/components/FriendSelect/style'
import '../../common/components/CreateTeamModal/style'
import '../../common/components/GroupAvatarSelect/style'
import '../../common/components/CrudeAvatar/style'
import '../../common/components/ComplexAvatar/style'
import '../../common/components/CommonParseSession/style'
import '../../common/components/Welcome/style'

import './index.less'
