import 'antd/lib/modal/style'
import 'antd/lib/popover/style'
import 'antd/lib/button/style'
import 'antd/lib/message/style'
import 'antd/lib/input/style'

import '../../../common/components/GroupAvatarSelect/style'
import '../../../common/components/FriendSelect/style'
import '../../../common/components/SearchInput/style'

import './addItem.less'
import './addList.less'
import './addModal.less'
import './addPanel.less'
import './createModal.less'
