import './groupList.less'
import './groupItem.less'
import './groupDetail.less'
import './groupPower.less'
import './index.less'

import 'antd/lib/form/style'
import 'antd/lib/input/style'
import 'antd/lib/button/style'
import 'antd/lib/select/style'
import 'antd/lib/modal/style'
import 'antd/lib/switch/style'
import 'antd/lib/radio/style'
import 'antd/lib/message/style'
import 'antd/lib/empty/style'
