import 'antd/lib/modal/style'
import 'antd/lib/popover/style'
import 'antd/lib/button/style'
import 'antd/lib/message/style'
import 'antd/lib/input/style'

import '@xkit-yx/common-ui/es/components/GroupAvatarSelect/style'
import '@xkit-yx/common-ui/es/components/FriendSelect/style'
import '@xkit-yx/common-ui/es/components/SearchInput/style'

import './addItem.less'
import './addList.less'
import './addModal.less'
import './addPanel.less'
import './createModal.less'
