import 'antd/lib/button/style'
import 'antd/lib/input/style'
import 'antd/lib/form/style'
import 'antd/lib/modal/style'
import 'antd/lib/divider/style'
import 'antd/lib/message/style'
import './index.less'
