import '@xkit-yx/common-ui/es/components/FriendSelect/style'
import '@xkit-yx/common-ui/es/components/GroupAvatarSelect/style'
import '@xkit-yx/common-ui/es/components/CrudeAvatar/style'
import '@xkit-yx/common-ui/es/components/ComplexAvatar/style'
import '@xkit-yx/common-ui/es/components/CommonParseSession/style'
import '@xkit-yx/common-ui/es/components/Welcome/style'
import '@xkit-yx/common-ui/es/components/MyUserCard/style'
import '@xkit-yx/common-ui/es/components/UserCard/style'
import '@xkit-yx/common-ui/es/components/SearchInput/style'

import '@xkit-yx/conversation-kit-ui/es/style'
import '@xkit-yx/contact-kit-ui/es/black-list/style'
import '@xkit-yx/contact-kit-ui/es/friend-list/style'
import '@xkit-yx/contact-kit-ui/es/group-list/style'
import '@xkit-yx/contact-kit-ui/es/contact-list/style'
import '@xkit-yx/chat-kit-ui/es/style'
import '@xkit-yx/search-kit-ui/es/add/style'
import '@xkit-yx/search-kit-ui/es/search/style'
