import '../components/ChatActionBar/style'
import '../components/ChatSettingDrawer/style'
import '../components/ChatHeader/style'
import '../components/ChatP2pMessageList/style'
import '../components/ChatMessageItem/style'
import '../components/ChatMessageInput/style'
import '../components/ChatAddMembers/style'
import '../components/ChatCreateTeam/style'
import '../components/ChatP2pSetting/style'
import '../components/ChatTeamSetting/style'

import '../../../common-ui/src/components/FriendSelect/style'
import '../../../common-ui/src/components/GroupAvatarSelect/style'
import '../../../common-ui/src/components/CrudeAvatar/style'
import '../../../common-ui/src/components/ComplexAvatar/style'
import '../../../common-ui/src/components/CommonParseSession/style'
import '../../../common-ui/src/components/Welcome/style'

import './index.less'
